# Generated by Django 4.1.3 on 2022-11-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meals_options_meals_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='slug',
        ),
    ]
